GitHub CI, README and BASH Improvements
Dichloromethane/skat pull request #2
Opened 2020-11-16 13:58 UTC by jpylypiw

GitHub CI tests the following aspects:
- Markdownlint for README
- Shellcheck for Shell Scripts
- Execute a test build on Ubuntu 20.04

Shell Improvements:
- Fix Shebang black line
- Variable Escaping
- Parameters with integer instead of strings

2020-11-16 14:06 UTC, iTitus requested changes
Thanks a lot, but there a few nitpicks left :)

2020-11-16 14:06 UTC, iTitus commented on README.md
> +- -p _print_graph_ instead of creating an image, the structure is printed in JSON format
this option does not require an argument, it is a flag. Can you make that clearer?
Also the format is called [DOT](https://en.wikipedia.org/wiki/DOT_%28graph_description_language%29).

2020-11-16 14:06 UTC, iTitus commented on README.md
> +- -l _include_libs_ when creating the graph the libraries are displayed in addition to the own classes
This is also just a flag

2020-11-16 14:06 UTC, iTitus commented on README.md
> +- g++
Can we instead use `build-essential` here? This should cover all bases and install gcc, make and the libraries
```suggestion
- build-essential
```

2020-11-16 14:06 UTC, iTitus commented on .github/workflows/build.yml
> +          sudo apt-get install -y libglfw3-dev libfreetype-dev g++
```suggestion
          sudo apt-get install -y libglfw3-dev libfreetype-dev build-essential
```

2020-11-22 00:53 UTC, iTitus requested changes

2020-11-22 00:53 UTC, iTitus commented on tools/dep_graph.sh
> +      if [ $include_libs -gt 0 ]; then
There is some inconsistency here. I think you need to do this:
```suggestion
      if [ "$include_libs" -ne 0 ]; then
```

2020-11-22 00:53 UTC, iTitus commented on tools/dep_graph.sh
> +} | if [ "${print_graph}" -ge 0 ]; then
```suggestion
} | if [ "${print_graph}" -ne 0 ]; then
```

2020-11-22 10:41 UTC, jpylypiw commented
Resolved the issues in latest commits 😄 
Found a typo and corrected it directly.

2020-11-22 12:04 UTC, merged